subscription_id = "Eneter your subscription ID here"
client_id       = "Enter your client ID here"
client_secret   = "Enter your client secret here"
tenant_id       = "Enter your tenant ID here"
location        = "Central India"
resource_group_name = "rg-redis-private"
